intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{immer}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{immer}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

if $config.libimmer.no_exceptions
{
  lib{quill}: cxx.export.poptions += -DIMMER_NO_EXCEPTIONS
}
else
{
  lib{quill}: cxx.export.poptions += -DIMMER_USE_EXCEPTIONS
}

# Install into the immer/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/immer/
  install.subdirs = true
}
