lib{immer}: {hxx ixx txx}{**}

# Export options.
#
src_pfx = [dir_path] $src_root/include/

lib{immer}:
{
  cxx.export.poptions = "-I$src_pfx"
}

if $config.libimmer.no_exceptions
{
  lib{immer}: cxx.export.poptions += -DIMMER_NO_EXCEPTIONS
}
else
{
  lib{immer}: cxx.export.poptions += -DIMMER_USE_EXCEPTIONS
}

# Install into the immer/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/immer/
  install.subdirs = true
}
